[workspace]
members = [
    "gn-client",
    "gn-common",
    "gn-node",
    "gn-oracle",
    "gn-pallets/pallet-chainlink",
    "gn-pallets/pallet-guild",
    "gn-pallets/pallet-test-caller",
    "gn-runtime",
    "gn-test-runtime",
    "gn-wasm",
    "gn-frontend",
]
# don't include wasm in the build process
default-members = [
    "gn-client",
    "gn-common",
    "gn-node",
    "gn-oracle",
    "gn-pallets/pallet-chainlink",
    "gn-pallets/pallet-guild",
    "gn-pallets/pallet-test-caller",
    "gn-runtime",
    "gn-test-runtime",
]

[profile.release]
panic = "abort"
