[workspace]
members = [
    "node",
    "pallets/pallet-chainlink",
    "pallets/pallet-guild",
    "pallets/pallet-test-caller",
    "pallets/test-runtime",
    "runtime",
]
[profile.release]
panic = "abort"
