[package]
name = "gn-common"
version = "0.0.0-alpha"
edition = "2021"

[features]
reqcheck = ["anyhow", "ethers-core", "providers", "std"]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "scale-info/std",
]

[dependencies]
# local
providers = { path = "../rusty-gate/providers", optional = true }

# general
anyhow = { version = "1.0", default-features = false, optional = true }
ethers-core = { version = "1.0.2", default-features = false, optional = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { version = "1.0.144", default-features = false, features = ["derive"] }

[dev-dependencies]
async-trait = { version = "0.1.57", default-features = false }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
