name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: formatting
    runs-on: rust
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-09-14
          override: true
          profile: minimal

      - uses: actions/checkout@v2

      - name: api-keys from secret
        run: |
          mkdir .api-keys
          printf ${{ secrets.ETHERSCAN_API_KEY }} >> .api-keys/etherscan-api-key
          printf ${{ secrets.BALANCY_API_KEY }} >> .api-keys/balancy-api-key

      - name: build
        run: cargo build --color=always --all-targets --all-features

      - name: add-nightly-clippy
        run: rustup component add clippy --toolchain nightly-2022-09-14

      - name: clippy
        run: cargo clippy --color=always --all-targets --all-features --examples --tests

      - name: test
        run: |
          cargo t --color=always
          cargo t --color=always --features flood-tests
