[package]
name = "gn-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
console_error_panic_hook = "0.1.7"
gn-client = { path = "../gn-client", default-features = false, features = ["wasm"] }
gn-common = { path = "../gn-common" }
js-sys = "0.3.60"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3.6", features = ["Window", "console"] }

[dev-dependencies]
tracing-wasm = "0.2.1"
wasm-bindgen-test = "0.3.24"
