name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Update submodules
        run: |
          git -c "url.https://x-access-token:${{ secrets.SUBMODULE_TOKEN }}@github.com/.insteadOf=https://github.com/" pull --recurse-submodules
          git -c "url.https://x-access-token:${{ secrets.SUBMODULE_TOKEN }}@github.com/.insteadOf=https://github.com/" submodule update --init --recursive --remote

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.test
          context: .
          push: false
