name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.RUSTY_GATE }}

      - name: Checkout submodules
        run: |
          git config --system http.sslVerify false
          git config --system user.email "email@email.com"
          git submodule update --init --recursive

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.test
          context: .
          push: false
