name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
      ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}
      POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
      BSC_RPC: ${{ secrets.BSC_RPC }}
      GNOSIS_RPC: ${{ secrets.GNOSIS_RPC }}
      FANTOM_RPC: ${{ secrets.FANTOM_RPC }}
      AVALANCHE_RPC: ${{ secrets.AVALANCHE_RPC }}
      ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
      CELO_RPC: ${{ secrets.CELO_RPC }}
      HARMONY_RPC: ${{ secrets.HARMONY_RPC }}
      HECO_RPC: ${{ secrets.HECO_RPC }}
      GOERLI_RPC: ${{ secrets.GOERLI_RPC }}
      OPTIMISM_RPC: ${{ secrets.OPTIMISM_RPC }}
      MOONRIVER_RPC: ${{ secrets.MOONRIVER_RPC }}
      RINKEBY_RPC: ${{ secrets.RINKEBY_RPC }}
      METIS_RPC: ${{ secrets.METIS_RPC }}
      CRONOS_RPC: ${{ secrets.CRONOS_RPC }}
      BOBA_RPC: ${{ secrets.BOBA_RPC }}
      PALM_RPC: ${{ secrets.PALM_RPC }}

    steps:
      - uses: actions/checkout@v3

      - name: Update submodules 
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          pacman --noconfirm -Sy lsof
          lsof $SSH_AUTH_SOCK | awk 'NR > 1 {print $2}' | xargs kill -15
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.RUSTY_GATE }}"
          git submodule update --init --recursive --remote

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.test
          context: .
          push: false
