name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    name: formatting
    runs-on: rust
    steps:
      - uses: actions/checkout@v3
      - run: cargo fmt -- --check
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - uses: actions/checkout@v2

      - name: install wasm toolchain
        run: rustup target add wasm32-unknown-unknown

      - name: add-nightly-clippy
        run: rustup component add clippy --toolchain nightly

      - name: clippy
        run: cargo clippy --color=always --all-features --tests --workspace --exclude node-template

      - name: test
        run: cargo test --all-features --workspace --exclude node-template
