name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well

    steps:
      - uses: actions/checkout@v3

      - name: Update submodules
        run: |
          eval `ssh-agent -s`
          random=$(date +%s)
          ssh-agent -a /tmp/ssh_agent_${random}.sock > /dev/null
          ssh-add - <<< "${{ secrets.RUSTY_GATE }}"
          git submodule update --init --recursive --remote

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.test
          context: .
          push: false
          build-args: |
            ETHEREUM_RPC_TOKEN=${{ secrets.ETHEREUM_RPC_TOKEN }}
            POLYGON_RPC_TOKEN=${{ secrets.POLYGON_RPC_TOKEN }}
            GOERLI_RPC_TOKEN=${{ secrets.GOERLI_RPC_TOKEN }}
            ARBITRUM_RPC_TOKEN=${{ secrets.ARBITRUM_RPC_TOKEN }}
            PALM_RPC_TOKEN=${{ secrets.PALM_RPC_TOKEN }}
            METIS_RPC_TOKEN=${{ secrets.METIS_RPC_TOKEN }}
