name: general code check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: rust

    env:
      RUSTFLAGS: -Dwarnings # fails on warnings as well
    steps:
      - uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.test
          context: .
          push: false
